package com.forest.basic.mybatis.model;

public class Tauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.cdesc
     *
     * @mbggenerated
     */
    private String cdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.cseq
     *
     * @mbggenerated
     */
    private Long cseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.curl
     *
     * @mbggenerated
     */
    private String curl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.cpid
     *
     * @mbggenerated
     */
    private Long cpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.menu_level
     *
     * @mbggenerated
     */
    private Long menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.rpt_filename
     *
     * @mbggenerated
     */
    private String rptFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tauth.menu_icon
     *
     * @mbggenerated
     */
    private String menuIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.cid
     *
     * @return the value of tauth.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.cid
     *
     * @param cid the value for tauth.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.cdesc
     *
     * @return the value of tauth.cdesc
     *
     * @mbggenerated
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.cdesc
     *
     * @param cdesc the value for tauth.cdesc
     *
     * @mbggenerated
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.cname
     *
     * @return the value of tauth.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.cname
     *
     * @param cname the value for tauth.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.cseq
     *
     * @return the value of tauth.cseq
     *
     * @mbggenerated
     */
    public Long getCseq() {
        return cseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.cseq
     *
     * @param cseq the value for tauth.cseq
     *
     * @mbggenerated
     */
    public void setCseq(Long cseq) {
        this.cseq = cseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.curl
     *
     * @return the value of tauth.curl
     *
     * @mbggenerated
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.curl
     *
     * @param curl the value for tauth.curl
     *
     * @mbggenerated
     */
    public void setCurl(String curl) {
        this.curl = curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.cpid
     *
     * @return the value of tauth.cpid
     *
     * @mbggenerated
     */
    public Long getCpid() {
        return cpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.cpid
     *
     * @param cpid the value for tauth.cpid
     *
     * @mbggenerated
     */
    public void setCpid(Long cpid) {
        this.cpid = cpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.menu_level
     *
     * @return the value of tauth.menu_level
     *
     * @mbggenerated
     */
    public Long getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.menu_level
     *
     * @param menuLevel the value for tauth.menu_level
     *
     * @mbggenerated
     */
    public void setMenuLevel(Long menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.token
     *
     * @return the value of tauth.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.token
     *
     * @param token the value for tauth.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.category
     *
     * @return the value of tauth.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.category
     *
     * @param category the value for tauth.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.rpt_filename
     *
     * @return the value of tauth.rpt_filename
     *
     * @mbggenerated
     */
    public String getRptFilename() {
        return rptFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.rpt_filename
     *
     * @param rptFilename the value for tauth.rpt_filename
     *
     * @mbggenerated
     */
    public void setRptFilename(String rptFilename) {
        this.rptFilename = rptFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tauth.menu_icon
     *
     * @return the value of tauth.menu_icon
     *
     * @mbggenerated
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tauth.menu_icon
     *
     * @param menuIcon the value for tauth.menu_icon
     *
     * @mbggenerated
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }
}