package com.forest.basic.mybatis.model;

public class Troletauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troletauth.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troletauth.cauthid
     *
     * @mbggenerated
     */
    private Long cauthid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column troletauth.croleid
     *
     * @mbggenerated
     */
    private Long croleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troletauth.cid
     *
     * @return the value of troletauth.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troletauth.cid
     *
     * @param cid the value for troletauth.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troletauth.cauthid
     *
     * @return the value of troletauth.cauthid
     *
     * @mbggenerated
     */
    public Long getCauthid() {
        return cauthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troletauth.cauthid
     *
     * @param cauthid the value for troletauth.cauthid
     *
     * @mbggenerated
     */
    public void setCauthid(Long cauthid) {
        this.cauthid = cauthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column troletauth.croleid
     *
     * @return the value of troletauth.croleid
     *
     * @mbggenerated
     */
    public Long getCroleid() {
        return croleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column troletauth.croleid
     *
     * @param croleid the value for troletauth.croleid
     *
     * @mbggenerated
     */
    public void setCroleid(Long croleid) {
        this.croleid = croleid;
    }
}