package com.forest.basic.mybatis.model;

public class Trole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trole.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trole.cdesc
     *
     * @mbggenerated
     */
    private String cdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trole.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trole.cid
     *
     * @return the value of trole.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trole.cid
     *
     * @param cid the value for trole.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trole.cdesc
     *
     * @return the value of trole.cdesc
     *
     * @mbggenerated
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trole.cdesc
     *
     * @param cdesc the value for trole.cdesc
     *
     * @mbggenerated
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trole.cname
     *
     * @return the value of trole.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trole.cname
     *
     * @param cname the value for trole.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }
}