package com.forest.basic.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tuser
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tuser
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tuser
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public TuserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tuser
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCidIsNull() {
			addCriterion("cid is null");
			return (Criteria) this;
		}

		public Criteria andCidIsNotNull() {
			addCriterion("cid is not null");
			return (Criteria) this;
		}

		public Criteria andCidEqualTo(Long value) {
			addCriterion("cid =", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotEqualTo(Long value) {
			addCriterion("cid <>", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidGreaterThan(Long value) {
			addCriterion("cid >", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidGreaterThanOrEqualTo(Long value) {
			addCriterion("cid >=", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLessThan(Long value) {
			addCriterion("cid <", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidLessThanOrEqualTo(Long value) {
			addCriterion("cid <=", value, "cid");
			return (Criteria) this;
		}

		public Criteria andCidIn(List<Long> values) {
			addCriterion("cid in", values, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotIn(List<Long> values) {
			addCriterion("cid not in", values, "cid");
			return (Criteria) this;
		}

		public Criteria andCidBetween(Long value1, Long value2) {
			addCriterion("cid between", value1, value2, "cid");
			return (Criteria) this;
		}

		public Criteria andCidNotBetween(Long value1, Long value2) {
			addCriterion("cid not between", value1, value2, "cid");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeIsNull() {
			addCriterion("ccreatedatetime is null");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeIsNotNull() {
			addCriterion("ccreatedatetime is not null");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeEqualTo(Date value) {
			addCriterion("ccreatedatetime =", value, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeNotEqualTo(Date value) {
			addCriterion("ccreatedatetime <>", value, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeGreaterThan(Date value) {
			addCriterion("ccreatedatetime >", value, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ccreatedatetime >=", value, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeLessThan(Date value) {
			addCriterion("ccreatedatetime <", value, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeLessThanOrEqualTo(Date value) {
			addCriterion("ccreatedatetime <=", value, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeIn(List<Date> values) {
			addCriterion("ccreatedatetime in", values, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeNotIn(List<Date> values) {
			addCriterion("ccreatedatetime not in", values, "ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeBetween(Date value1, Date value2) {
			addCriterion("ccreatedatetime between", value1, value2,
					"ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCcreatedatetimeNotBetween(Date value1, Date value2) {
			addCriterion("ccreatedatetime not between", value1, value2,
					"ccreatedatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeIsNull() {
			addCriterion("cmodifydatetime is null");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeIsNotNull() {
			addCriterion("cmodifydatetime is not null");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeEqualTo(Date value) {
			addCriterion("cmodifydatetime =", value, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeNotEqualTo(Date value) {
			addCriterion("cmodifydatetime <>", value, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeGreaterThan(Date value) {
			addCriterion("cmodifydatetime >", value, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("cmodifydatetime >=", value, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeLessThan(Date value) {
			addCriterion("cmodifydatetime <", value, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeLessThanOrEqualTo(Date value) {
			addCriterion("cmodifydatetime <=", value, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeIn(List<Date> values) {
			addCriterion("cmodifydatetime in", values, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeNotIn(List<Date> values) {
			addCriterion("cmodifydatetime not in", values, "cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeBetween(Date value1, Date value2) {
			addCriterion("cmodifydatetime between", value1, value2,
					"cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCmodifydatetimeNotBetween(Date value1, Date value2) {
			addCriterion("cmodifydatetime not between", value1, value2,
					"cmodifydatetime");
			return (Criteria) this;
		}

		public Criteria andCnameIsNull() {
			addCriterion("cname is null");
			return (Criteria) this;
		}

		public Criteria andCnameIsNotNull() {
			addCriterion("cname is not null");
			return (Criteria) this;
		}

		public Criteria andCnameEqualTo(String value) {
			addCriterion("cname =", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameNotEqualTo(String value) {
			addCriterion("cname <>", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameGreaterThan(String value) {
			addCriterion("cname >", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameGreaterThanOrEqualTo(String value) {
			addCriterion("cname >=", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameLessThan(String value) {
			addCriterion("cname <", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameLessThanOrEqualTo(String value) {
			addCriterion("cname <=", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameLike(String value) {
			addCriterion("cname like", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameNotLike(String value) {
			addCriterion("cname not like", value, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameIn(List<String> values) {
			addCriterion("cname in", values, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameNotIn(List<String> values) {
			addCriterion("cname not in", values, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameBetween(String value1, String value2) {
			addCriterion("cname between", value1, value2, "cname");
			return (Criteria) this;
		}

		public Criteria andCnameNotBetween(String value1, String value2) {
			addCriterion("cname not between", value1, value2, "cname");
			return (Criteria) this;
		}

		public Criteria andCpwdIsNull() {
			addCriterion("cpwd is null");
			return (Criteria) this;
		}

		public Criteria andCpwdIsNotNull() {
			addCriterion("cpwd is not null");
			return (Criteria) this;
		}

		public Criteria andCpwdEqualTo(String value) {
			addCriterion("cpwd =", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdNotEqualTo(String value) {
			addCriterion("cpwd <>", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdGreaterThan(String value) {
			addCriterion("cpwd >", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdGreaterThanOrEqualTo(String value) {
			addCriterion("cpwd >=", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdLessThan(String value) {
			addCriterion("cpwd <", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdLessThanOrEqualTo(String value) {
			addCriterion("cpwd <=", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdLike(String value) {
			addCriterion("cpwd like", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdNotLike(String value) {
			addCriterion("cpwd not like", value, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdIn(List<String> values) {
			addCriterion("cpwd in", values, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdNotIn(List<String> values) {
			addCriterion("cpwd not in", values, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdBetween(String value1, String value2) {
			addCriterion("cpwd between", value1, value2, "cpwd");
			return (Criteria) this;
		}

		public Criteria andCpwdNotBetween(String value1, String value2) {
			addCriterion("cpwd not between", value1, value2, "cpwd");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andDistrictIdIsNull() {
			addCriterion("district_id is null");
			return (Criteria) this;
		}

		public Criteria andDistrictIdIsNotNull() {
			addCriterion("district_id is not null");
			return (Criteria) this;
		}

		public Criteria andDistrictIdEqualTo(Long value) {
			addCriterion("district_id =", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdNotEqualTo(Long value) {
			addCriterion("district_id <>", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdGreaterThan(Long value) {
			addCriterion("district_id >", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdGreaterThanOrEqualTo(Long value) {
			addCriterion("district_id >=", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdLessThan(Long value) {
			addCriterion("district_id <", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdLessThanOrEqualTo(Long value) {
			addCriterion("district_id <=", value, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdIn(List<Long> values) {
			addCriterion("district_id in", values, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdNotIn(List<Long> values) {
			addCriterion("district_id not in", values, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdBetween(Long value1, Long value2) {
			addCriterion("district_id between", value1, value2, "districtId");
			return (Criteria) this;
		}

		public Criteria andDistrictIdNotBetween(Long value1, Long value2) {
			addCriterion("district_id not between", value1, value2,
					"districtId");
			return (Criteria) this;
		}

		public Criteria andFullnameIsNull() {
			addCriterion("fullname is null");
			return (Criteria) this;
		}

		public Criteria andFullnameIsNotNull() {
			addCriterion("fullname is not null");
			return (Criteria) this;
		}

		public Criteria andFullnameEqualTo(String value) {
			addCriterion("fullname =", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotEqualTo(String value) {
			addCriterion("fullname <>", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameGreaterThan(String value) {
			addCriterion("fullname >", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameGreaterThanOrEqualTo(String value) {
			addCriterion("fullname >=", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameLessThan(String value) {
			addCriterion("fullname <", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameLessThanOrEqualTo(String value) {
			addCriterion("fullname <=", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameLike(String value) {
			addCriterion("fullname like", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotLike(String value) {
			addCriterion("fullname not like", value, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameIn(List<String> values) {
			addCriterion("fullname in", values, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotIn(List<String> values) {
			addCriterion("fullname not in", values, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameBetween(String value1, String value2) {
			addCriterion("fullname between", value1, value2, "fullname");
			return (Criteria) this;
		}

		public Criteria andFullnameNotBetween(String value1, String value2) {
			addCriterion("fullname not between", value1, value2, "fullname");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNull() {
			addCriterion("telephone is null");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNotNull() {
			addCriterion("telephone is not null");
			return (Criteria) this;
		}

		public Criteria andTelephoneEqualTo(String value) {
			addCriterion("telephone =", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotEqualTo(String value) {
			addCriterion("telephone <>", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThan(String value) {
			addCriterion("telephone >", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("telephone >=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThan(String value) {
			addCriterion("telephone <", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThanOrEqualTo(String value) {
			addCriterion("telephone <=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLike(String value) {
			addCriterion("telephone like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotLike(String value) {
			addCriterion("telephone not like", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneIn(List<String> values) {
			addCriterion("telephone in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotIn(List<String> values) {
			addCriterion("telephone not in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneBetween(String value1, String value2) {
			addCriterion("telephone between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotBetween(String value1, String value2) {
			addCriterion("telephone not between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andProfessionIsNull() {
			addCriterion("profession is null");
			return (Criteria) this;
		}

		public Criteria andProfessionIsNotNull() {
			addCriterion("profession is not null");
			return (Criteria) this;
		}

		public Criteria andProfessionEqualTo(String value) {
			addCriterion("profession =", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotEqualTo(String value) {
			addCriterion("profession <>", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionGreaterThan(String value) {
			addCriterion("profession >", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionGreaterThanOrEqualTo(String value) {
			addCriterion("profession >=", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLessThan(String value) {
			addCriterion("profession <", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLessThanOrEqualTo(String value) {
			addCriterion("profession <=", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionLike(String value) {
			addCriterion("profession like", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotLike(String value) {
			addCriterion("profession not like", value, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionIn(List<String> values) {
			addCriterion("profession in", values, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotIn(List<String> values) {
			addCriterion("profession not in", values, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionBetween(String value1, String value2) {
			addCriterion("profession between", value1, value2, "profession");
			return (Criteria) this;
		}

		public Criteria andProfessionNotBetween(String value1, String value2) {
			addCriterion("profession not between", value1, value2, "profession");
			return (Criteria) this;
		}

		public Criteria andJobsIsNull() {
			addCriterion("jobs is null");
			return (Criteria) this;
		}

		public Criteria andJobsIsNotNull() {
			addCriterion("jobs is not null");
			return (Criteria) this;
		}

		public Criteria andJobsEqualTo(String value) {
			addCriterion("jobs =", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsNotEqualTo(String value) {
			addCriterion("jobs <>", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsGreaterThan(String value) {
			addCriterion("jobs >", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsGreaterThanOrEqualTo(String value) {
			addCriterion("jobs >=", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsLessThan(String value) {
			addCriterion("jobs <", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsLessThanOrEqualTo(String value) {
			addCriterion("jobs <=", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsLike(String value) {
			addCriterion("jobs like", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsNotLike(String value) {
			addCriterion("jobs not like", value, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsIn(List<String> values) {
			addCriterion("jobs in", values, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsNotIn(List<String> values) {
			addCriterion("jobs not in", values, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsBetween(String value1, String value2) {
			addCriterion("jobs between", value1, value2, "jobs");
			return (Criteria) this;
		}

		public Criteria andJobsNotBetween(String value1, String value2) {
			addCriterion("jobs not between", value1, value2, "jobs");
			return (Criteria) this;
		}

		public Criteria andCompanyIsNull() {
			addCriterion("company is null");
			return (Criteria) this;
		}

		public Criteria andCompanyIsNotNull() {
			addCriterion("company is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyEqualTo(String value) {
			addCriterion("company =", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotEqualTo(String value) {
			addCriterion("company <>", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyGreaterThan(String value) {
			addCriterion("company >", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyGreaterThanOrEqualTo(String value) {
			addCriterion("company >=", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLessThan(String value) {
			addCriterion("company <", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLessThanOrEqualTo(String value) {
			addCriterion("company <=", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyLike(String value) {
			addCriterion("company like", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotLike(String value) {
			addCriterion("company not like", value, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyIn(List<String> values) {
			addCriterion("company in", values, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotIn(List<String> values) {
			addCriterion("company not in", values, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyBetween(String value1, String value2) {
			addCriterion("company between", value1, value2, "company");
			return (Criteria) this;
		}

		public Criteria andCompanyNotBetween(String value1, String value2) {
			addCriterion("company not between", value1, value2, "company");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tuser
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tuser
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}