package com.forest.basic.mybatis.model;

public class Tusertrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusertrole.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusertrole.croleid
     *
     * @mbggenerated
     */
    private Long croleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tusertrole.cuserid
     *
     * @mbggenerated
     */
    private Long cuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusertrole.cid
     *
     * @return the value of tusertrole.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusertrole.cid
     *
     * @param cid the value for tusertrole.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusertrole.croleid
     *
     * @return the value of tusertrole.croleid
     *
     * @mbggenerated
     */
    public Long getCroleid() {
        return croleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusertrole.croleid
     *
     * @param croleid the value for tusertrole.croleid
     *
     * @mbggenerated
     */
    public void setCroleid(Long croleid) {
        this.croleid = croleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tusertrole.cuserid
     *
     * @return the value of tusertrole.cuserid
     *
     * @mbggenerated
     */
    public Long getCuserid() {
        return cuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tusertrole.cuserid
     *
     * @param cuserid the value for tusertrole.cuserid
     *
     * @mbggenerated
     */
    public void setCuserid(Long cuserid) {
        this.cuserid = cuserid;
    }
}