package com.forest.basic.mybatis.model;

import java.util.Date;

public class Tuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.cid
	 * @mbggenerated
	 */
	private Long cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.ccreatedatetime
	 * @mbggenerated
	 */
	private Date ccreatedatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.cmodifydatetime
	 * @mbggenerated
	 */
	private Date cmodifydatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.cname
	 * @mbggenerated
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.cpwd
	 * @mbggenerated
	 */
	private String cpwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.district_id
	 * @mbggenerated
	 */
	private Long districtId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.fullname
	 * @mbggenerated
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.telephone
	 * @mbggenerated
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.profession
	 * @mbggenerated
	 */
	private String profession;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.jobs
	 * @mbggenerated
	 */
	private String jobs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.company
	 * @mbggenerated
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tuser.address
	 * @mbggenerated
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.cid
	 * @return  the value of tuser.cid
	 * @mbggenerated
	 */
	public Long getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.cid
	 * @param cid  the value for tuser.cid
	 * @mbggenerated
	 */
	public void setCid(Long cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.ccreatedatetime
	 * @return  the value of tuser.ccreatedatetime
	 * @mbggenerated
	 */
	public Date getCcreatedatetime() {
		return ccreatedatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.ccreatedatetime
	 * @param ccreatedatetime  the value for tuser.ccreatedatetime
	 * @mbggenerated
	 */
	public void setCcreatedatetime(Date ccreatedatetime) {
		this.ccreatedatetime = ccreatedatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.cmodifydatetime
	 * @return  the value of tuser.cmodifydatetime
	 * @mbggenerated
	 */
	public Date getCmodifydatetime() {
		return cmodifydatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.cmodifydatetime
	 * @param cmodifydatetime  the value for tuser.cmodifydatetime
	 * @mbggenerated
	 */
	public void setCmodifydatetime(Date cmodifydatetime) {
		this.cmodifydatetime = cmodifydatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.cname
	 * @return  the value of tuser.cname
	 * @mbggenerated
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.cname
	 * @param cname  the value for tuser.cname
	 * @mbggenerated
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.cpwd
	 * @return  the value of tuser.cpwd
	 * @mbggenerated
	 */
	public String getCpwd() {
		return cpwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.cpwd
	 * @param cpwd  the value for tuser.cpwd
	 * @mbggenerated
	 */
	public void setCpwd(String cpwd) {
		this.cpwd = cpwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.email
	 * @return  the value of tuser.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.email
	 * @param email  the value for tuser.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.district_id
	 * @return  the value of tuser.district_id
	 * @mbggenerated
	 */
	public Long getDistrictId() {
		return districtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.district_id
	 * @param districtId  the value for tuser.district_id
	 * @mbggenerated
	 */
	public void setDistrictId(Long districtId) {
		this.districtId = districtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.fullname
	 * @return  the value of tuser.fullname
	 * @mbggenerated
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.fullname
	 * @param fullname  the value for tuser.fullname
	 * @mbggenerated
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.telephone
	 * @return  the value of tuser.telephone
	 * @mbggenerated
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.telephone
	 * @param telephone  the value for tuser.telephone
	 * @mbggenerated
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.profession
	 * @return  the value of tuser.profession
	 * @mbggenerated
	 */
	public String getProfession() {
		return profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.profession
	 * @param profession  the value for tuser.profession
	 * @mbggenerated
	 */
	public void setProfession(String profession) {
		this.profession = profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.jobs
	 * @return  the value of tuser.jobs
	 * @mbggenerated
	 */
	public String getJobs() {
		return jobs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.jobs
	 * @param jobs  the value for tuser.jobs
	 * @mbggenerated
	 */
	public void setJobs(String jobs) {
		this.jobs = jobs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.company
	 * @return  the value of tuser.company
	 * @mbggenerated
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.company
	 * @param company  the value for tuser.company
	 * @mbggenerated
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tuser.address
	 * @return  the value of tuser.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tuser.address
	 * @param address  the value for tuser.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}