package com.forest.basic.mybatis.dao;

import com.forest.basic.mybatis.model.Tauth;
import com.forest.basic.mybatis.model.TauthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TauthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int countByExample(TauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int deleteByExample(TauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int insert(Tauth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int insertSelective(Tauth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	List<Tauth> selectByExample(TauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	Tauth selectByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Tauth record,
			@Param("example") TauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Tauth record,
			@Param("example") TauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Tauth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tauth
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Tauth record);
}