package com.forest.basic.mybatis.dao;

import com.forest.basic.mybatis.model.Troletauth;
import com.forest.basic.mybatis.model.TroletauthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TroletauthMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int countByExample(TroletauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int deleteByExample(TroletauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int insert(Troletauth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int insertSelective(Troletauth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	List<Troletauth> selectByExample(TroletauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	Troletauth selectByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Troletauth record,
			@Param("example") TroletauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Troletauth record,
			@Param("example") TroletauthExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Troletauth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table troletauth
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Troletauth record);
}