package com.forest.basic.mybatis.dao;

import com.forest.basic.mybatis.model.Trole;
import com.forest.basic.mybatis.model.TroleExample;
import com.forest.basic.vo.config.auth.VORole;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TroleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int countByExample(TroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int deleteByExample(TroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int insert(Trole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int insertSelective(Trole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	List<Trole> selectByExample(TroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	Trole selectByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Trole record,
			@Param("example") TroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Trole record,
			@Param("example") TroleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Trole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trole
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Trole record);

	// add
 	int countRoleList(VORole role);

 	List<Trole> queryRoleList(VORole role);
}