package com.forest.basic.mybatis.dao;

import com.forest.basic.mybatis.model.Tauth;
import com.forest.basic.mybatis.model.Tuser;
import com.forest.basic.mybatis.model.TuserExample;
import com.forest.basic.vo.config.auth.VOUser;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TuserMapper {
    

	// add
 	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int countByExample(TuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int deleteByExample(TuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int insert(Tuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int insertSelective(Tuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	List<Tuser> selectByExample(TuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	Tuser selectByPrimaryKey(Long cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Tuser record,
			@Param("example") TuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Tuser record,
			@Param("example") TuserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Tuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tuser
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Tuser record);

	int countUserList(VOUser user);

 	List<VOUser> queryUserList(VOUser user);

 	List<Tauth> queryTuserAuthRole(Long userId);
 	
 	List<Tauth> queryHeaderAuths(Long userId);
 	
 	List<Tauth> querySubAuths(@Param("userId") Long userId, @Param("menuId") Long menuId);

}